src/Entity/Capsule.php
<?php

namespace App\Entity;

use App\Repository\CapsuleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CapsuleRepository::class)
 */
class Capsule
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $kind;

    /**
     * @ORM\Column(type="string", length=10000)
     */
    private $attached_files;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expiration_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $owner_email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $archived;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $recipients;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKind(): ?string
    {
        return $this->kind;
    }

    public function setKind(string $kind): self
    {
        $this->kind = $kind;

        return $this;
    }

    public function getAttachedFiles(): ?array
    {
        if ($this->attached_files)
            return unserialize($this->attached_files);
        return null;
    }

    public function setAttachedFiles(array $attached_files): self
    {
        $this->attached_files = serialize($attached_files);

        return $this;
    }

    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expiration_date;
    }

    public function setExpirationDate(\DateTimeInterface $expiration_date): self
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    public function getOwnerEmail(): ?string
    {
        return $this->owner_email;
    }

    public function setOwnerEmail(string $owner_email): self
    {
        $this->owner_email = $owner_email;

        return $this;
    }

    public function getArchived(): ?bool
    {
        return $this->archived;
    }

    public function setArchived(bool $archived): self
    {
        $this->archived = $archived;

        return $this;
    }

    public function getRecipients(): array
    {
        if (!$this->recipients)
            return [];
        return unserialize($this->recipients);
    }

    public function setRecipients(?array $recipients): self
    {
        if (!$recipients)
            $this->recipients = null;
        else
            $this->recipients = serialize($recipients);

        return $this;
    }

    public function hasExpired(): bool {
        return $this->getExpirationDate() < new \DateTime();
    }

    public function generateCode(): ?string
    {
        if ($this->code)
            return $this->code;

        $this->code = "";
        $alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        for ($i = 0; $i < 6; $i++) {
            $this->code .= $alphabet[rand(0, strlen($alphabet) - 1)];
        }

        return $this->code;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }
}

templates/about.html.twig
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>< volverse código ></title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <script defer src="js/about.js" type="text/javascript"></script>
    <link href="styles/index.css" rel="stylesheet" />
  </head>
  <body>
    <main class="main-about">
      <div class="nav flex border--purple">
        <div class="logo">
          <h4><a href="{{ path('capsules') }}">< volverse código ></a></h4>
        </div>
        <div class="nav-menu flex">
          <a class="nav-menu__item" href="#">Quienes Somos</a>
          <a class="nav-menu__item search">Search</a>
        </div>
      </div>
      <div class="width-container about-container">
        <h4 class="intro-title">Quiénes Somos</h4>
        <div class="letters">
          <h3 class="link" id="JB" onclick="mostrarCapsula(this)">JB</h3>
          <h3 class="link" id="ET" onclick="mostrarCapsula(this)">ET</h3>
          <h3 class="link" id="JM" onclick="mostrarCapsula(this)">JM</h3>
          <h3 class="link" id="VB" onclick="mostrarCapsula(this)">VB</h3>
          <h3 class="link" id="RV" onclick="mostrarCapsula(this)">RV</h3>
          <h3 class="link" id="RDB" onclick="mostrarCapsula(this)">RDB</h3>
        </div>
      </div>
    </main>
    <div class="modal-container">
      <div class="modal-content">
        <div id="file"></div>
        <div id="file-info">
          <p id="close-capsule" onclick="cerrarCapsula()">X</p>
          <p id="open-date"></p>
        </div>
      </div>
    </div>
  </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/capsule-single.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/styles/index.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script defer src="/js/upload.js" type="text/javascript"></script>

    <title>< volverse código ></title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  </head>
  <body>
    {% if capsule %}
      <div class="container centered">
        <h2>{{ capsule.ownerEmail }}</h2>
          {% if capsule.hasExpired %}
          <div class="archivo" style="height: 300px; width: 300px; background-color: beige">
          {% if capsule.kind == 'image' %}
            {% for file in capsule.attachedFiles %}
              <img style="max-width: 100%; max-height: 100%" alt="{{ capsule.code }}" src="/uploads/{{ file }}" />
            {% endfor %}
          {% elseif capsule.kind == 'video' %}
            {% for file in capsule.attachedFiles %}
              <video style="max-width: 100%; max-height: 100%" controls src="/uploads/{{ file }}"></video>
            {% endfor %}
          {% elseif capsule.kind == 'audio' %}
            {% for file in capsule.attachedFiles %}
              <audio style="max-width: 100%; max-height: 100%" controls src="/uploads/{{ file }}"></audio>
            {% endfor %}
          {% else %}
            {% for file in capsule.attachedFiles %}
              <a href="/uploads/{{ file }}">{{ file }}</a>
            {% endfor %}
          {% endif %}
          </div>
          <p>Esta cápsula se abrió el <span>{{ capsule.expirationDate|date('d/m/Y') }}</span></p>
          {% else %}
          <p>Esta cápsula se abrirá el <span>{{ capsule.expirationDate|date('d/m/Y') }}</span></p>
          {% endif %}
      </div>
    {% else %}
      <div class="container centered">
        <h2>¡Cápsula no encontrada!</h2>
      </div>
    {% endif %}


    <!-- jQuery -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"
      type="text/javascript"
    ></script>
    <!-- jQuery easing plugin -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
      type="text/javascript"
    ></script>
  </body>
</html>

templates/capsules-list.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="styles/index.css" />
    <script defer src="/js/capsules.js" type="text/javascript"></script>
    <title>< volverse código ></title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  </head>
  <body>
    <div class="nav flex border--purple">
      <div class="logo">
        <h4><a href="#">< volverse código ></a></h4>
      </div>
      <div class="nav-menu flex">
        <a class="nav-menu__item" href="{{ path('about') }}">Quienes Somos</a>
        <a class="nav-menu__item search">Search</a>
      </div>
    </div>

    <div class="lista">
      {% for row in capsules %}
        <div class="texto-vertical">
          {% for capsule in row %}
            <a href="/capsula/{{ capsule.id }}" class="link" onclick="abrirImagen()">{{ capsule.letter }}</a>
          {% endfor %}
        </div>
      {% endfor %}

    <!-- jQuery -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"
      type="text/javascript"
    ></script>
    <!-- jQuery easing plugin -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
      type="text/javascript"
    ></script>
  </body>
</html>

templates/index.html.twig
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>< volverse código ></title>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <script defer src="js/index.js" type="text/javascript"></script>
  <link href="styles/index.css" rel="stylesheet" />
</head>
<body>
<div class="video-container">
      <audio id="index-audio" src="assets/audio/video_audio.mp3"></audio>

      <video playsinline autoplay muted class="bgvid">
        <source src="assets/videos/intro.mp4" type="video/mp4" />
      </video>

      <div class="btn-container">
        <a href="{{ path('intro') }}#" class="btn border--white">Crear Cápsula</a>
        <a href="{{ path('capsules') }}" class="btn border--white">Ver Cápsulas</a>
      </div>
    </div>

    <div class="play-container">
      <div class="play-content">
        <img
          src="assets/img/play-button.png"
          alt="play button"
          id="play-button"
        />
      </div>
    </div>
</body>
</html>

templates/intro.html.twig
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>< volverse código ></title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <script defer src="js/intro.js" type="text/javascript"></script>
    <link href="styles/index.css" rel="stylesheet" />
  </head>
  <body>
    <audio autoplay id="player">
      <source src="assets/audio/sunrise.mp3" type="audio/mpeg" />
    </audio>
    <main>
      <div class="intro-container">
        <h2 class="intro-title" id="frase-0">
          <span class="link" onclick="mostrar(this)"
            >¿Cómo crear tu cápsula?</span
          >
        </h2>
        <p class="frase" id="frase-1">
          Aferrate a eso que te hace <br /><span
            class="link"
            onclick="mostrar(this)"
            >ser quien sos</span
          >
        </p>
        <p class="frase" id="frase-2">
          <span class="link" onclick="mostrar(this)">Abrazalo</span>,
          apretujalo, mirale las arrugas
        </p>
        <p class="frase" id="frase-3">
          Primero acompañalo<br />Naden un rato juntos<br />Dejalo nadar
          <span class="link" onclick="mostrar(this)">solo</span>
        </p>
        <p class="frase" id="frase-4">
          Andá <span class="link" onclick="mostrar(this)">soltandolo</span> de a
          poquito
        </p>
        <p class="frase" id="frase-5">
          Cuando te de des cuenta
          <span class="link" onclick="mostrar(this)">ya no está más</span>
        </p>
        <p class="frase" id="frase-6">
          Lo abraza
          <span class="link" onclick="mostrar(this)">otra</span> persona
        </p>
        <p class="frase" id="frase-7">
          Le mira las arrugas de <br />la misma forma que<br />
          <span class="link" onclick="mostrar(this)">las miraste vos</span>
        </p>
        <p class="frase" id="frase-8">
          Pero <span class="link" onclick="mostrar(this)">ya no son</span> las
          mismas
        </p>
        <p class="frase" id="frase-9">
          Forman
          <span class="link" onclick="mostrarTodo()">otro rostro</span>
        </p>
        <a href="{{ path('upload') }}" class="btn border--pink intro-button">></a>
      </div>
    </main>
  </body>
</html>

templates/upload-complete.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="styles/index.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script defer src="js/upload.js" type="text/javascript"></script>

    <title>Volverse Código</title>
  </head>
  <body>
    <div class="container centered">
      <h2>GRACIAS POR TU SUBIDA</h2>
      <h3>Tu código es <span id="capsule-code">{{ code }}</span></h3>
      <p>
        Podés ir a ver
        <a class="text-purple" href="/capsula/{{ code }}">TU CÁPSULA</a>
      </p>
      <p>
        o podes ver
        <a class="text-purple" href="{{ path('capsules') }}"
          >cápsulas de otras personas ></a
        >
      </p>
    </div>

    <!-- jQuery -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"
      type="text/javascript"
    ></script>
    <!-- jQuery easing plugin -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
      type="text/javascript"
    ></script>
  </body>
</html>

templates/upload.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="styles/index.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script defer src="js/upload.js" type="text/javascript"></script>

    <title>Volverse Código</title>
  </head>
  <body>
    <div class="box">
      <div class="glitch">
        <div class="glitch__img"></div>
        <div class="glitch__img"></div>
        <div class="glitch__img"></div>
        <div class="glitch__img"></div>
        <div class="glitch__img"></div>
      </div>
    </div>
    <!-- multistep form -->
    {{ form_start(form, {'attr': {'id': 'msform'}}) }}
      <!-- progressbar -->
      <ul id="progressbar">
        <li class="active"></li>
        <li></li>
        <li></li>
      </ul>
      <!-- fieldsets -->
      <fieldset>
        <h2>¿ Qué tipo de cápsula querés crear ?</h2>
        <hr class="border--pink" />
        <div class="opciones">
          <ul class="capsule-types">
            <li class="type">
              {{ form_widget(form.kind.children[0], {'id': 'radio1', 'attr': {'class': 'radio-button'}}) }}
              <label for="radio1">Audio</label>
            </li>

            <li class="type">
              {{ form_widget(form.kind.children[1], {'id': 'radio2', 'attr': {'class': 'radio-button'}}) }}
              <label for="radio2">Video</label>
            </li>
            <li class="type">
              {{ form_widget(form.kind.children[2], {'id': 'radio3', 'attr': {'class': 'radio-button'}}) }}
              <label for="radio3">Texto</label>
            </li>
            <li class="type">
              {{ form_widget(form.kind.children[3], {'id': 'radio4', 'attr': {'class': 'radio-button'}}) }}
              <label for="radio4">Imagen</label>
            </li>
          </ul>
        </div>
        <a class="next btn border--pink action-button right">Siguiente</a>
      </fieldset>
      <fieldset>
        <div class="file-box">
          {{ form_widget(form.file, {
            'id': 'input-file',
            'attr': {
              'data-multiple-caption': "{count} files selected",
            }}) }}
          <label for="input-file"><span>< Subí tu archivo ></span></label>
        </div>
        <label for="date-input">Elegí la fecha en la que se podrá abrir:</label>
        {{ form_widget(form.expirationDate, {'id': 'date-input'}) }}
        <label for="email">Ingresá tu mail:</label>
        {{ form_widget(form.ownerEmail, {'id': 'email'}) }}
        <a class="previous btn border--pink action-button left">Volver</a>
        {{  form_widget(form.submit, {'label': 'Siguiente', 'attr': {
              'class': 'next btn border--pink action-button right'
        }}) }}
      </fieldset>
      <fieldset>
      <div class="sk-fading-circle">
  <div class="sk-circle1 sk-circle"></div>
  <div class="sk-circle2 sk-circle"></div>
  <div class="sk-circle3 sk-circle"></div>
  <div class="sk-circle4 sk-circle"></div>
  <div class="sk-circle5 sk-circle"></div>
  <div class="sk-circle6 sk-circle"></div>
  <div class="sk-circle7 sk-circle"></div>
  <div class="sk-circle8 sk-circle"></div>
  <div class="sk-circle9 sk-circle"></div>
  <div class="sk-circle10 sk-circle"></div>
  <div class="sk-circle11 sk-circle"></div>
  <div class="sk-circle12 sk-circle"></div>
</div>
        <h2>Tus archivos están siendo cargados</h2>
        
      </fieldset>
    {{  form_end(form, {'render_rest': false}) }}

    <!-- jQuery -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"
      type="text/javascript"
    ></script>
    <!-- jQuery easing plugin -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
      type="text/javascript"
    ></script>
  </body>
</html>